### ISSUE TITLE
Unable to set colours over the LAN protocol.

### ISSUE THREAD

**Issue by abjugard** [nmelo/homebridge-lifx#7]
As the issue states, this plugin is unable to change the LIFX lights colours via the LAN protocol.

**Comment by Bluebie** [comment]
I'm seeing this issue too. Library works fine without lan mode enabled, but with the original (kickstarter) lifx bulbs, lan protocol works fine for turning the lights on and off, but does not work for setting any of the colour attributes. the homebridge console log displays the brightness, saturation, and hue changes accurately - just the bulbs never update these characteristics over lan.

i'm looking in to it now.

**Comment by nmelo** [comment]
👍
